### ISSUE TITLE
Cannot get property values to display in XML or JSON files.

### ISSUE THREAD

**Issue by kenthub** [markjprice/cs8dotnetcore3#11]
I have been unsuccessful in getting the properties of the product to display in my XML and JSON. I have reviewed your code against mine and could not determine any variations in the Category, Product, or Northwind classes. 

I even straight copied your code from those classes into mine after a few attempts but with no success. If anyone could look at it and see what I'm missing that would be great! I tried using the debugger on the actual item in the foreach loop but wasn't sure how to really trace what was going on. 

Link to my GitHub: [here](https://github.com/kenthub/Exercise02)

**XML** code preview:
```
<?xml version="1.0" encoding="utf-8"?>
<categories>
  <category id="1" name="Beverages" description="Soft drinks, coffees, teas, beers, and ales" count="0">
    <products />
  </category>
  <category id="2" name="Condiments" description="Sweet and savory sauces, relishes, spreads, and seasonings" count="0">
    <products />
  </category>
```

**JSON** code preview:
```{
  "categories": [
    {
      "id": 1,
      "name": "Beverages",
      "desc": "Soft drinks, coffees, teas, beers, and ales",
      "product_count": 0,
      "products": []
    },
    {
      "id": 2,
      "name": "Condiments",
      "desc": "Sweet and savory sauces, relishes, spreads, and seasonings",
      "product_count": 0,
      "products": []
    },
```

**Comment by markjprice** [comment]
The link you gave to your code in your GitHub repo returns a 404. But since your problem is empty Products for each Category, then even without seeing your code I'm guessing the most likely problem is a missing call to the Include method. For example, in the following statement which fetches the Products for each Category in the query:

IQueryable<Category> cats = db.Categories.Include(c => c.Products);

**Comment by kenthub** [comment]
I forgot since it was private that I needed to add you.

I do have the Include on my code in Program.cs since I tried copying most
of yours to see where the problem could have been.

**Comment by markjprice** [comment]
Hi Kent,

There are two things wrong in your Exercise02 solution.

1) You have imported the old EntityFramework 6.4 package:

<PackageReference Include="EntityFramework" Version="6.4.0" />

This is unnecessary because you will use the new Entity Framework Core packages. Delete the package reference above from your .csproj file.

2) You imported the old System.Data.Entity namespace from that old package to get the Include method. This Include method does not work with EF Core which is why it was not loading the Products. 

Replace:

using System.Data.Entity;

With:

using Microsoft.EntityFrameworkCore;

That will enable the correct Include method, and that will load the products. 

Good luck!
