### ISSUE TITLE
NorthwindCms Import fails

### ISSUE THREAD

**Issue by intrepion** [markjprice/cs8dotnetcore3#15]
Here are the steps I take and the errors I get:

```
git clone git@github.com:markjprice/cs8dotnetcore3.git
cd cs8dotnetcore3\PracticalApps\NorthwindCms
dotnet run
```

I then go to https://localhost:5001/import and I get this error:

```
 An exception occurred in the database while saving changes for context type 'Piranha.Data.EF.SQLite.SQLiteDb'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Piranha_Pages.SiteId, Piranha_Pages.Slug'.
```

okay, there is a duplicate.  Let's try from scratch

```
rm piranha.blog.db
dotnet run
```

I then go to https://localhost:5001/import again and I get this error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindCms.Controllers.ImportController.Import() in C:\code\cs8dotnetcore3\PracticalApps\NorthwindCms\Controllers\ImportController.cs:line 49
```

**Comment by markjprice** [comment]
Hi, I will have a look at this at the weekend. Thank you for raising the issue.

**Comment by markjprice** [comment]
The solution database already has the categories from Northwind imported as category page instances. When using the GitHub solution, you do not need to import the categories. 

The code was supposed to check this by attempting to find each category page using its slug, but one of the category names has a space in it so its slug contains a hyphen instead of a space, and I had not accounted for that in the checking code. I have now fixed this bug in the solution code. 

I also took the opportunity to add a message so that when the import is run, you will see how many categories are already in the database and how many have been newly imported.

<img width="962" alt="import-message" src="https://user-images.githubusercontent.com/14040265/83937958-e4ac0d00-a7c8-11ea-82e4-67c3d3ac1d36.png">

Thanks!
