### ISSUE TITLE
error message: "The '<' operator is reserved for future use"

### ISSUE THREAD

**Issue by Strydir** [markjprice/cs8dotnetcore3#33]
(4th Ed)
Windows 10 Powershell no longer recognizes the '<', which means that attempting to 

"pipe the script to SQLite to create the Northwind.db database as shown in the following command:  
sqlite3 Northwind.dp < Northwind.sql" 

will result in the error "The '<' operator is reserved for future use".

Use "-init" instead:    sqlite3 Northwind.db -init Northwind.sql

Source:  https://stackoverflow.com/questions/14765688/sqlite3-not-working-on-powershell

-I didn't know where else to put this information

**Comment by markjprice** [comment]
This is already in the errata:
https://github.com/markjprice/cs8dotnetcore3/blob/master/errata.md#page-363---creating-the-northwind-sample-database-for-sqlite

**Comment by Strydir** [comment]
I've encountered issues like this before with other textbooks: for my
future reference, how is a user supposed to find this information?  Are
there any common methods used?  I thought that "Readme"s were for this.
Should you rename it or something?  Would that even help?  Do other authors
use "errata"?  I would never think to look for a page called "errata" and I
would think that a non-native english speaker would be even less likely to
look there.  Lol, of course, a non-native english speaker might be MORE
likely due to the need to actually look up the definition of the word
"errata".

Anyway, that page looks very comprehensive and now that I have it, I should
be good to go, thank you.
Boy, things sure have changed!  In my day, there was no ability to update
or correct the information in a textbook short of buying the next edition
and hoping that the author caught the mistakes/updates!
Thanks for the work!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by markjprice** [comment]
Hi Strydir,

Errata is a standard term for a place to list mistakes and corrections in books. But I agree it is probably not the most common term especially for non-native English speakers. Thank you for the idea to make that title clearer. I have changed it now. Do you think it's better? 

Yes, I know what you mean about changes in modern book life, especially technical books. All the errata listed for the fourth edition were fixed in the fifth edition. And all errata listed for the fifth edition are being fixed in the sixth. But something always slips through. 

I'm using the GitHub repositories more and more to increase the useful lifetime of the print book. In the sixth edition I've added explicit instructions for how to find errata and raise issues in GitHub so hopefully more readers will find them easier. I'm also thinking of creating a Slack or Discord for the sixth edition and explain that in Chapter 1 too: do you think this kinds of interactions would be useful for readers? 

BTW, you will also find GitHub repos for the fifth (out now) and sixth editions (out on November 9, 2021). I don't know how useful they are without the matching book, but you might find them useful. And of course I would encourage you to get the sixth edition on November 9, 2021. ;-)

**Comment by Strydir** [comment]
Hi Mark!
Omg, yes!  Just tacking on that description makes a WORLD of difference!
Thank you!  I actually have a decent education and it's rather embarrassing
to admit that I didn't pick up that "errata" was exactly what I was looking
for.

"But something always slips through":  ain't that the truth!!  Nothing like
seeing a spelling mistake that makes it past multiple Editors, lol!!

I like the idea of using Github like that!!  I think that is the way to
go.  I have other textbooks that I never made it thru because of all the
hoops that I would have had to jump thru to get those corrections.  I find
it absolutely amazing just how fast C# is growing/changing!

As far as the Discord goes, I like the idea but I'm not sure that you'd get
enough action to warrant the server usage. It kind of depends on what
you're willing to do with it:  I'd join it so that I could ask questions
but I think that that approach will end up with you providing "lectures"
that you might not have anticipated.  In other words, I think that you'd
get large amounts of inactivity, combined with times of really irritating
idiots asking really stupid questions.  So my "off the cuff" thought would
be to say no, just confine it to Github.  The fact that you're adding
instructions on where to find them should be enough.  Don't get me wrong:
I'd LOVE to have you available on a Discord!  I just don't think that you'd
like it so much, lol!!!  :D

Thanks for the info about the 6th Ed!  I was thinking of looking for the
next ed as I noticed the 5th being mentioned:  your timing on the 6th ed
should be about perfect for me!  If you think of it, let me know when it's
out!

Thank you very much!!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Strydir** [comment]
Almost forgot:  not a Slack user so I have no input there.  Maybe I should
be...

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by markjprice** [comment]
Hmmmm, yes, you're probably right about Discord. I think I will leave any mention of Discord or Slack out of Chapter 1 in the sixth edition and direct all enquires/issues to the GitHub repo as you suggest. Then I might experiment with channels like Slack and Discord for a select group. If you're interested, feel free to email me markjprice at gmail because I don't want to post publicly on here.
